# Generated by Django 4.2.18 on 2025-02-05 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecyclerOrders',
            new_name='RecyclerOrder',
        ),
    ]
